repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      -   id: check-yaml
      -   id: end-of-file-fixer
          exclude: docs/auto_examples
      -   id: trailing-whitespace
          exclude: docs/auto_examples
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix, --unsafe-fixes ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: pytest
        name: Pytest
        entry: uv run pytest
        stages: [ pre-push ]
        types: [python]
        language: system
        pass_filenames: false
